name: CI/CD Pipeline
 
on:
  push:
    branches:
      - main  # Change this to your main branch if necessary
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1
        with:
registry: .venkatdemoacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
 
      - name: Build Docker image
        run: |
docker build -t .azurecr.io/hello-app:latest .
 
      - name: Push Docker image
        run: |
docker push .azurecr.io/hello-app:latest
