name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: venkatdemoacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t venkatdemoacr.azurecr.io/hello-app:latest .

      - name: Push Docker image
        run: |
          docker push venkatdemoacr.azurecr.io/hello-app:latest

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group democluster_group --name democluster

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/hello-app hello-app=venkatdemoacr.azurecr.io/hello-app:latest --record
          kubectl rollout status deployment/hello-app
